"""create channel_config and wishlist_item

Revision ID: 67d81aaa4c98
Revises: 
Create Date: 2026-02-22 19:07:34.627079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d81aaa4c98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_config',
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('channel_id', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('guild_id', 'channel_id')
    )
    op.create_index('ix_channel_config_guild_channel', 'channel_config', ['guild_id', 'channel_id'], unique=False)
    op.create_table('wishlist_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_id', sa.String(length=32), nullable=False),
    sa.Column('channel_id', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('url_norm', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('price', sa.Text(), nullable=True),
    sa.Column('user_tag', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'url_norm', name='uq_wishlist_channel_urlnorm')
    )
    op.create_index('ix_wishlist_guild_channel_created', 'wishlist_item', ['guild_id', 'channel_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_wishlist_guild_channel_created', table_name='wishlist_item')
    op.drop_table('wishlist_item')
    op.drop_index('ix_channel_config_guild_channel', table_name='channel_config')
    op.drop_table('channel_config')
    # ### end Alembic commands ###
